remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: [Stocomp.ru]
description: [Ремонт компьютеров и ноутбуков Щёлково пн.-пят. с 10:00 до 18:00 +7 967 167-77-37]
show_downloads: ["true"]
google_analytics: [Your Google Analytics tracking ID]
